# Generated by Django 3.0.7 on 2021-02-25 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('araincdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempgrowth',
            name='client_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='araincdb.Client', verbose_name='Client Name'),
        ),
    ]
