# Generated by Django 3.0.7 on 2021-02-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('araincdb', '0004_keyword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keyword',
            new_name='Growthkeyword',
        ),
        migrations.AlterModelOptions(
            name='growthkeyword',
            options={'verbose_name': 'Growth Keyword', 'verbose_name_plural': 'Growth Keywords'},
        ),
    ]
