# Generated by Django 3.0.7 on 2021-02-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('araincdb', '0005_auto_20210225_1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Automatch',
        ),
    ]
