# Generated by Django 3.0.7 on 2021-02-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('araincdb', '0006_delete_automatch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListingStatus',
        ),
    ]
