# Generated by Django 3.0.7 on 2021-02-25 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('araincdb', '0007_delete_listingstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listingkeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, verbose_name='Keyword')),
                ('match_type', models.CharField(choices=[('ATM', 'Automatch'), ('PAM', 'Possible Auto Match'), ('ANM', 'Auto No Match')], default='ATM', max_length=3)),
                ('client_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='araincdb.Client', verbose_name='Client Name')),
            ],
            options={
                'verbose_name': 'Listing Keyword',
                'verbose_name_plural': 'Listing Keywords',
            },
        ),
    ]
