# Generated by Django 3.0.7 on 2021-02-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('araincdb', '0009_templisting_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templisting',
            name='username',
            field=models.CharField(max_length=200, verbose_name='Username'),
        ),
    ]
