# Generated by Django 3.0.7 on 2021-02-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('araincdb', '0010_auto_20210226_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Account Username'),
        ),
    ]
