# Generated by Django 3.0.7 on 2021-02-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('araincdb', '0011_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growth',
            name='profile_username',
            field=models.CharField(max_length=200, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='profile_username',
            field=models.CharField(max_length=200, verbose_name='Username'),
        ),
    ]
