# Generated by Django 3.0.7 on 2021-03-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('araincdb', '0012_auto_20210228_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='growth',
            name='growth_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Growth Start Time'),
        ),
        migrations.AddField(
            model_name='growth',
            name='screening_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Screening Start Time'),
        ),
        migrations.AddField(
            model_name='growth',
            name='unfollowing_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Unfollowing Start Time'),
        ),
        migrations.AddField(
            model_name='listing',
            name='cs_crosscheck_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='CS Crosscheck Start Time'),
        ),
        migrations.AddField(
            model_name='listing',
            name='cs_review_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='CS Review Start Time'),
        ),
        migrations.AddField(
            model_name='listing',
            name='cs_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='CS Start Time'),
        ),
        migrations.AddField(
            model_name='listing',
            name='ms_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Message Sending Start Time'),
        ),
        migrations.AddField(
            model_name='listing',
            name='oms_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OMS Start Time'),
        ),
        migrations.AddField(
            model_name='listing',
            name='screening_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Screening Start Time'),
        ),
        migrations.AlterField(
            model_name='growth',
            name='growthed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Growth End Time'),
        ),
        migrations.AlterField(
            model_name='growth',
            name='screened_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Screening End Date'),
        ),
        migrations.AlterField(
            model_name='growth',
            name='unfollowing_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Unfollowing End Time'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='cs_crosscheck_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='CS Crosscheck End Time'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='cs_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='CS End Time'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='cs_review_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='CS Review End Time'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='ms_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Message Sending End Time'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='oms_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OMS End Time'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='screened_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Screening End Time'),
        ),
    ]
