# Generated by Django 3.0.7 on 2021-03-09 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('araincdb', '0013_auto_20210306_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='assigned_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='araincdb.Client', verbose_name='Client'),
        ),
    ]
