# Generated by Django 3.0.7 on 2021-04-10 05:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('araincdb', '0014_employee_assigned_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Posturl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.CharField(max_length=200, unique=True, verbose_name='Post URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='Caption')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location')),
                ('input_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Input Date')),
            ],
            options={
                'verbose_name': 'Post URL',
                'verbose_name_plural': 'Post URLs',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='araincdb.Country', verbose_name='Country'),
        ),
    ]
