# Generated by Django 3.0.7 on 2021-04-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('araincdb', '0015_auto_20210410_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempPosturl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.CharField(max_length=200, verbose_name='Post URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='Caption')),
            ],
            options={
                'verbose_name': 'Temp Post URL',
                'verbose_name_plural': 'Temp Post URLs',
            },
        ),
        migrations.AddField(
            model_name='posturl',
            name='is_located',
            field=models.BooleanField(default=False, verbose_name='Input Date'),
        ),
    ]
