# Generated by Django 3.0.7 on 2021-04-24 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('araincdb', '0016_auto_20210410_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_username', models.CharField(max_length=200, verbose_name='Username')),
                ('scraping_status', models.CharField(max_length=200, verbose_name='Scraping Status')),
                ('external_url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='External URL')),
                ('profile_description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Profile Description')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Full Name')),
                ('caption', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Caption')),
                ('post_count', models.IntegerField(blank=True, null=True, verbose_name='Post Count')),
                ('followers', models.IntegerField(blank=True, null=True, verbose_name='Followers')),
                ('followings', models.IntegerField(blank=True, null=True, verbose_name='Followings')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Publication Date')),
                ('hashtag', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hashtag')),
                ('input_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Input Date')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location')),
                ('growth_review_status', models.CharField(blank=True, max_length=200, null=True, verbose_name='Growth Review Status')),
                ('screening_review_status', models.CharField(blank=True, max_length=200, null=True, verbose_name='Screening Review Status')),
                ('unfollowing_status', models.CharField(blank=True, max_length=200, null=True, verbose_name='Unfollowing Status')),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Remarks')),
                ('screening_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Screening Start Time')),
                ('screened_date', models.DateTimeField(blank=True, null=True, verbose_name='Screening End Date')),
                ('growth_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Growth Start Time')),
                ('growthed_date', models.DateTimeField(blank=True, null=True, verbose_name='Growth End Time')),
                ('unfollowing_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Unfollowing Start Time')),
                ('unfollowing_date', models.DateTimeField(blank=True, null=True, verbose_name='Unfollowing End Time')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Growth Date')),
                ('assigned_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='araincdb.Account', verbose_name='Assigned Account')),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='araincdb.Client', verbose_name='Client Name')),
                ('connection_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='araincdb.ConnectionStatus', verbose_name='Connection Status')),
                ('growth_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='araincdb.GrowthStatus', verbose_name='Growth Status')),
                ('growthed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Growth VA')),
                ('quality_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='araincdb.QualityStatus', verbose_name='Quality Status')),
                ('screened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Screening VA')),
                ('unfollowing_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Unfolloiwng VA')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Growth Archive',
                'verbose_name_plural': 'Growth Archive',
            },
        ),
    ]
