# Generated by Django 3.0.7 on 2021-04-24 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('araincdb', '0017_growtharchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='posturl',
            name='client_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='araincdb.Client', verbose_name='Client Name'),
        ),
        migrations.AddField(
            model_name='posturl',
            name='is_pushed_tempgrowth',
            field=models.BooleanField(default=False, verbose_name='Is Scrapped'),
        ),
        migrations.AddField(
            model_name='posturl',
            name='is_scrapped',
            field=models.BooleanField(default=False, verbose_name='Is Scrapped'),
        ),
        migrations.AddField(
            model_name='posturl',
            name='profile_username',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Username'),
        ),
        migrations.AddField(
            model_name='posturl',
            name='scrapped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Scrapped By'),
        ),
        migrations.AddField(
            model_name='tempposturl',
            name='client_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='araincdb.Client', verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='posturl',
            name='is_located',
            field=models.BooleanField(default=False, verbose_name='Is Located'),
        ),
    ]
