# Generated by Django 3.0.7 on 2021-04-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('araincdb', '0018_auto_20210424_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='posturl',
            name='hashtag',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hashtag'),
        ),
        migrations.AddField(
            model_name='posturl',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Publication Date'),
        ),
        migrations.AddField(
            model_name='posturl',
            name='scrapped_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scrapped Date'),
        ),
        migrations.AddField(
            model_name='tempposturl',
            name='hashtag',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hashtag'),
        ),
        migrations.AddField(
            model_name='tempposturl',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Publication Date'),
        ),
    ]
