# Generated by Django 3.0.7 on 2021-05-11 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('araincdb', '0020_auto_20210425_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growth',
            name='growth_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='araincdb.GrowthStatus', verbose_name='Growth Status'),
        ),
    ]
