# Generated by Django 3.0.7 on 2021-05-12 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('araincdb', '0022_growthdedupe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Growthunique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_username', models.CharField(max_length=200, verbose_name='Username')),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='araincdb.Client', verbose_name='Client Name')),
            ],
            options={
                'verbose_name': 'Growthunique',
                'verbose_name_plural': 'Growthunique',
            },
        ),
    ]
