# Generated by Django 3.0.7 on 2021-05-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('araincdb', '0023_growthunique'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempgrowth',
            name='followers',
            field=models.IntegerField(blank=True, null=True, verbose_name='Followers'),
        ),
        migrations.AddField(
            model_name='tempgrowth',
            name='followings',
            field=models.IntegerField(blank=True, null=True, verbose_name='Followings'),
        ),
        migrations.AddField(
            model_name='tempgrowth',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='tempgrowth',
            name='post_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Post Count'),
        ),
        migrations.AddField(
            model_name='tempgrowth',
            name='profile_description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Profile Description'),
        ),
    ]
