# Generated by Django 3.0.7 on 2021-05-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('araincdb', '0024_auto_20210512_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='growthdedupe',
            name='hashtag',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hashtag'),
        ),
        migrations.AddField(
            model_name='growthunique',
            name='hashtag',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hashtag'),
        ),
    ]
