# Generated by Django 3.0.7 on 2021-06-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('araincdb', '0025_auto_20210520_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growthkeyword',
            name='match_type',
            field=models.CharField(choices=[('ATM', 'Automatch'), ('PAM', 'Possible Auto Match'), ('ANM', 'Auto No Match'), ('PH2', 'Phase 2')], default='ATM', max_length=3),
        ),
    ]
