# Generated by Django 3.0.7 on 2021-07-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('araincdb', '0027_auto_20210726_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='caption',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='listing',
            name='hashtag',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hashtag'),
        ),
        migrations.AddField(
            model_name='listingdedupe',
            name='caption',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='listingdedupe',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='listingunique',
            name='caption',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='listingunique',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Location'),
        ),
    ]
