# Generated by Django 3.0.7 on 2021-07-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('araincdb', '0028_auto_20210728_0231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templisting',
            old_name='username',
            new_name='profile_username',
        ),
        migrations.AddField(
            model_name='templisting',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='templisting',
            name='profile_description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Profile Description'),
        ),
        migrations.AddField(
            model_name='templisting',
            name='scraping_status',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Scraping Status'),
        ),
    ]
