# Generated by Django 3.0.7 on 2021-08-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('araincdb', '0029_auto_20210730_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='cs',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='CS'),
        ),
    ]
