# Generated by Django 3.0.7 on 2021-09-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('araincdb', '0030_auto_20210802_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='growth',
            name='language_score',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Language Score'),
        ),
    ]
