# Generated by Django 3.0.7 on 2021-09-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('araincdb', '0031_growth_language_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleFileUplaoder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_username', models.CharField(max_length=200, verbose_name='Username')),
                ('profile_description', models.CharField(blank=True, max_length=20000, null=True, verbose_name='Profile Description')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Full Name')),
                ('hashtag', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hashtag')),
            ],
            options={
                'verbose_name': 'Multiple File Uploader',
                'verbose_name_plural': 'Multiple Files Uploader',
            },
        ),
    ]
